for i,v in pairs(game:GetService("CoreGui"):GetChildren()) do
    if v.Name == "Discord" then
       v:Destroy()
    end
end

game.Players.LocalPlayer.Character.Humanoid.WalkSpeed = 16

getgenv().walk = game.Players.LocalPlayer.Character.Humanoid.WalkSpeed;

local vu = game:GetService("VirtualUser")
game:GetService("Players").LocalPlayer.Idled:connect(function()
   vu:Button2Down(Vector2.new(0,0),workspace.CurrentCamera.CFrame)
   wait(1)
   vu:Button2Up(Vector2.new(0,0),workspace.CurrentCamera.CFrame)
end)


function Best()
    local v14 = require(game.Players.LocalPlayer.PlayerScripts.ClientModules)

    local v23 = v14.Variables
    local v24 = v23.Data
    local v25 = v24.CurrentTool
    local v27 = v25 + 1
    local v28 = string.format("%0.2i", v27)
return v28
end

function AE()
    for i,v in pairs(game:GetService("Workspace").MapItems.Items:GetChildren()) do
        if v.Name == tostring(Best()) then
            fireproximityprompt(v.Attachment.ProximityPrompt)
        end
    end
end


local DiscordLib = loadstring(game:HttpGet"https://raw.githubusercontent.com/dawid-scripts/UI-Libs/main/discord%20lib.txt")()

local win = DiscordLib:Window(game:GetService("MarketplaceService"):GetProductInfo(game.PlaceId).Name)

local serv = win:Server("gui", "")

local btns = serv:Channel("af")

btns:Label("Hello, user: "..game.Players.LocalPlayer.Name)
btns:Label("I'm dev: SpaceCat#1748 in Discord")

local pl = game.Players.LocalPlayer
local char = pl.Character
local humpr = char.HumanoidRootPart
local hum = char.Humanoid
local amv = game:GetService("Players").LocalPlayer.PlayerGui.Side.Stats.Bars.Strength.Amount
local amp = tonumber(game:GetService("Players").LocalPlayer.PlayerGui.Side.Stats.Bars.Strength.Amount.Text)

btns:Button("Strength = current strength", function()
game:GetService("RunService").RenderStepped:Connect(function()
game:GetService("Players").LocalPlayer.PlayerGui.Side.Stats.Bars.Strength.Amount.Text = game:GetService("Workspace")[game.Players.LocalPlayer.Name].Head.OverheadUI.Stats.Strength.Value.Text
end)
end)

btns:Toggle("Auto-Equip Best Tool(if reached power)",false, function(state)
getgenv().ebt = state

game:GetService("RunService").RenderStepped:Connect(function()
    if getgenv().ebt == true then
        AE()
    end
end)
end)

btns:Toggle("Auto-click",false, function(state)
getgenv().clcv1 = state

game:GetService("RunService").RenderStepped:Connect(function()
    if getgenv().clcv1 == true then
        for i,v in pairs(pl.Backpack:GetChildren()) do
            if v:IsA("Tool") then
               hum:EquipTool(v)
            end
        end
        vu:ClickButton1(Vector2.new(9e9,9e9))
    end
end)
end)

local delaysell

btns:Textbox("Delay of sell", "Type here!", true, function(v)
delaysell = v
end)

btns:Toggle("Auto-Sell",false, function(state)
getgenv().sssvc5 = state

while wait(delaysell) do
    if getgenv().sssvc5 == true then
         humpr.CFrame = game:GetService("Workspace").__THINGS.Sell.Touch.CFrame
         firetouchinterest(humpr, game:GetService("Workspace").__THINGS.Sell.Touch.TouchInterest.Parent, 0)
         firetouchinterest(humpr, game:GetService("Workspace").__THINGS.Sell.Touch.TouchInterest.Parent, 1)
    end
end
end)

btns:Toggle("Auto-Claim Achievements",false, function(state)
getgenv().ca = state

game:GetService("RunService").RenderStepped:Connect(function()
    if getgenv().ca == true then
        for i,v in pairs(game:GetService("Players").LocalPlayer.PlayerGui.AchievementsUI.Frame.ScrollingFrame.Frame:GetChildren()) do
    if v.ClassName == "Frame" then
        local args = {
            [1] = v.Name
        }

        game:GetService("ReplicatedStorage").Assets.Network.ClaimAchievementReward:FireServer(unpack(args))
    end
end

    end
end)
end)

local egg = serv:Channel("Eggs")

eggTable = {}
for _,v in pairs(game:GetService("ReplicatedStorage").Assets.Eggs:GetChildren()) do
    if not table.find(eggTable, v.Name) then
       table.insert(eggTable, v.Name)
    end
end

local selectedegg
local drop = egg:Dropdown("Pick Egg", eggTable, function(v)
print(v)
selectedegg = v
end)

egg:Toggle("Auto-Buy Egg", false, function(state)
getgenv().buy1 = state

while wait() do
    if getgenv().buy1 == true then
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = selectedegg,
    [2] = false
}

game:GetService("ReplicatedStorage").Assets.Network.HatchEgg:InvokeServer(unpack(args))
    end
end
end)

egg:Toggle("Auto-Equip Best", false, function(state)
getgenv().best = state

while wait() do
    if getgenv().best == true then
-- Script generated by SimpleSpy - credits to exx#9394

game:GetService("ReplicatedStorage").Assets.Network.EquipBestPets:FireServer()
    end
end
end)

egg:Toggle("Auto-Craft All", false, function(state)
getgenv().craft = state

while wait() do
    if getgenv().craft == true then
        game:GetService("ReplicatedStorage").Assets.Network.CraftAll:FireServer()
    end
end
end)

local msc = serv:Channel("Misc")

msc:Textbox("WalkSpeed", "Type here!", true, function(v)
getgenv().walk = v

game.Players.LocalPlayer.Character.Humanoid.WalkSpeed = getgenv().walk
end)

msc:Toggle("Toggle WalkSpeed",false, function(state)
getgenv().walk1 = state

game:GetService("RunService").RenderStepped:Connect(function()
    if getgenv().walk1 == true then
        game.Players.LocalPlayer.Character.Humanoid.WalkSpeed = getgenv().walk
    elseif getgenv().walk1 == false then
        game.Players.LocalPlayer.Character.Humanoid.WalkSpeed = 16
    end
end)
end)



msc:Button("Infinity Jumps", function()
local InfiniteJumpEnabled = true
game:GetService("UserInputService").JumpRequest:connect(function()
	if InfiniteJumpEnabled then
		player.Character:FindFirstChildOfClass'Humanoid':ChangeState("Jumping")
	end
end)
end)