for i,v in pairs(game:GetService("CoreGui"):GetChildren()) do
    if v.Name == "Discord" then
       v:Destroy()
    end
end

eggTable = {}
for _,v in pairs(game:GetService("Workspace").Eggs.Check:GetChildren()) do
    if not table.find(eggTable, v.Name) then
       table.insert(eggTable, v.Name)
    end
end



getgenv().walk = game.Players.LocalPlayer.Character.Humanoid.WalkSpeed;

local GetName = game:GetService("MarketplaceService"):GetProductInfo(game.PlaceId)

local vu = game:GetService("VirtualUser")
game:GetService("Players").LocalPlayer.Idled:connect(function()
   vu:Button2Down(Vector2.new(0,0),workspace.CurrentCamera.CFrame)
   wait(1)
   vu:Button2Up(Vector2.new(0,0),workspace.CurrentCamera.CFrame)
end)

local VirtualInputManager = game:GetService('VirtualInputManager')

local player = game.Players.LocalPlayer

local DiscordLib = loadstring(game:HttpGet"https://raw.githubusercontent.com/dawid-scripts/UI-Libs/main/discord%20lib.txt")()

local win = DiscordLib:Window(GetName.Name)

local serv = win:Server("gui", "")

local auf = serv:Channel("Farm")


auf:Toggle("Auto-Farm",false, function(state)
getgenv().af = state

game:GetService("RunService").RenderStepped:Connect(function()
    if getgenv().af == true then
        if game:GetService("Workspace").GameInfo.GameTime.Value > 0 then
            game.Players.LocalPlayer.Character.Humanoid:MoveTo(game:GetService("Workspace").CheckFolder.Ready.Position)
        elseif game:GetService("Workspace").GameInfo.GameTime.Value == 0 then
            for i,v in pairs(game:GetService("Workspace").Room:GetChildren()) do
                for i,l in pairs(v.Mob:GetChildren()) do
                    if l:FindFirstChild("Humanoid") then
                        game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = l.HumanoidRootPart.CFrame
                        local args = {
                            [1] = l.Humanoid
                        }

                        game:GetService("ReplicatedStorage").Remote.Event.Fight["[C-S]TakeDamage"]:FireServer(unpack(args))
                    end
                end
            end
        end
    end
end)
end)

auf:Toggle("Auto-Collect Quest(even if you dont unlock these quests)",false, function(state)
getgenv().quest = state

game:GetService("RunService").RenderStepped:Connect(function()
    if getgenv().quest == true then
     for i,v in pairs(game:GetService("Players").LocalPlayer.PlayerGui.Quest.Frame.Main.List:GetChildren()) do
    if v.ClassName == "Frame" then
local args = {
    [1] = v.Name
}

game:GetService("ReplicatedStorage").Remote.Event.DailyMission["[C-S]PlayerGetReward"]:FireServer(unpack(args))
    end
end
    end
end)
end)

local egg = serv:Channel("Eggs")

local selectedegg
local drop = egg:Dropdown("Pick Egg", eggTable, function(v)
print(v)
selectedegg = v
end)

egg:Toggle("Auto-Buy Egg", false, function(state)
getgenv().buy1 = state

while wait() do
    if getgenv().buy1 == true then
        local args = {
            [1] = selectedegg
        }

        game:GetService("ReplicatedStorage").Remote.Function.Luck["[C-S]DoLuck"]:InvokeServer(unpack(args))
    end
end
end)


egg:Toggle("Auto-Equip Best Pets", false, function(state)
getgenv().best = state

while wait() do
    if getgenv().best == true then
-- Script generated by SimpleSpy - fixed version for exploits other than synapse & krnl made by stummy#002 credits to exx#9394 for originally creating the script.

game:GetService("ReplicatedStorage").Remote.Event.Pet["[C-S]TryEquipBest"]:FireServer()

    end
end
end)


local msc = serv:Channel("Misc")

msc:Textbox("WalkSpeed", "Type here!", true, function(v)
getgenv().walk = v

game.Players.LocalPlayer.Character.Humanoid.WalkSpeed = getgenv().walk
end)

msc:Toggle("Toggle WalkSpeed",false, function(state)
getgenv().walk1 = state

game:GetService("RunService").RenderStepped:Connect(function()
    if getgenv().walk1 == true then
        game.Players.LocalPlayer.Character.Humanoid.WalkSpeed = getgenv().walk
    elseif getgenv().walk1 == false then
        game.Players.LocalPlayer.Character.Humanoid.WalkSpeed = 16
    end
end)
end)



msc:Button("Infinity Jumps", function()
local InfiniteJumpEnabled = true
game:GetService("UserInputService").JumpRequest:connect(function()
	if InfiniteJumpEnabled then
		player.Character:FindFirstChildOfClass'Humanoid':ChangeState("Jumping")
	end
end)
end)

msc:Button("God Mode", function()
while wait() do
local args = {
    [1] = 100
}

game:GetService("ReplicatedStorage").Remote.Event.Up["[C-S]TryRegen"]:FireServer(unpack(args))
end
end)